# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node on Windows
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: demo_wepa_1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Node.js using Chocolatey
      run: |
        # Download and install Chocolatey
        iex ((New-Object System.Net.WebClient).DownloadString('https://install.chocolatey.org/install.ps1'))
        # Install Node.js using Chocolatey
        choco install nodejs --version=${{ matrix.node-version }}
    - name: Set Node.js Path
      run: |
        Set-Path -AppendVariable PATH "${env:ChocolateyInstall}\bin"
    - run: |
      npm install
    - run: |
      PLAYWRIGHT_JUNIT_OUTPUT_NAME=junit.xml npx playwright test --reporter=junit,line
    - name: "Import results to Xray"
      uses: mikepenz/xray-action@v2.3.0
      with:
        # Use API token instead of username/password
        apiToken: ${{ secrets.JIRA_API_TOKEN }}
        xrayCloud: "false"  # Assuming self-hosted Jira
        xrayBaseUrl: ${{ secrets.JIRA_BASEURL }}
        testFormat: "junit"
        testPaths: "**/xray-report.xml"
        testPlanKey: "${{ secrets.JIRA_TEST_PLAN_KEY }}"
        projectKey: "${{ secrets.JIRA_PROJECT_KEY }}"
        testEnvironments: "NODE_${{ matrix.node-version }}"
